name: JoeJones
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.4894
title: Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a28164'
    - '#fa6c54'
    - '#113044'
    - '#eeede9'
    - '#417e9f'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
