name: JoeJones
favicon: null
layout_spectrum: 0.76108
typography_spectrum: 0.18304
title: Jones
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a28164'
    - '#fa6c54'
    - '#113044'
    - '#eeede9'
    - '#417e9f'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
