name: JoeJones
favicon: null
layout_spectrum: 0.4171676381956786
typography_spectrum: 0.916872538626194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.08396825729869306
  lightness: 0.34448420093394816
  saturation: 0.7507146766874939
  rhythmicContrast: 0.6719363199081272
purpose: []
